---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipelinerun-
  annotations:
    "appstudio.redhat.com/updateComponentOnSuccess": "false"
  labels:
    pipelines.appstudio.openshift.io/type: "build"
    pipelines.openshift.io/used-by: "build-cloud"
    pipelines.openshift.io/runtime: "nodejs"
    pipelines.openshift.io/strategy: "s2i"
    build.appstudio.openshift.io/component: "component-sample"
spec:
  pipelineRef:
    name: build-pipeline-pass
    bundle: quay.io/kpavic/test-bundle:build-pipeline-pass
  params:
    - name: output-image
      value: "quay.io/redhat-appstudio/sample-image"
